CREATE DATABASE IF NOT EXISTS user_db 
CHARACTER SET utf8mb4;
USE user_db;
CREATE TABLE IF NOT EXISTS user(
   id  INT PRIMARY KEY auto_increment,
   name  VARCHAR(20) NOT NULL,
   age INT NOT NULL,
   email VARCHAR(50) NOT NULL UNIQUE,
   password VARCHAR(20) NOT NULL,
   create_time DATETIME DEFAULT CURRENT_TIMESTAMP
)